<a href="https://colab.research.google.com/github/menezescarlos/Python-Data-Science/blob/main/w3schools.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy

In [2]:
arr = numpy.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


In [5]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


In [4]:
# consultando a versão da biblioteca numpy
print(np.__version__)

1.23.5


In [6]:
arr = np.array([1, 2, 3, 4, 5])

print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [8]:
arr = np.array([[1, 2, 3, 4, 5],[1, 2, 3, 4, 5]])

print(arr)
print(type(arr))

[[1 2 3 4 5]
 [1 2 3 4 5]]
<class 'numpy.ndarray'>


In [10]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
'''
  Acessando elementos de um array
'''
print(arr[1])

2


In [13]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
'''
  Acessando elementos de um array
'''
print(arr[1] + arr[3])

6


In [24]:
import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('Localizando elementos Array 2D: ', arr[0, 1], arr[1,1])

Localizando elementos Array 2D:  2 7


In [25]:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(arr[0, 1, 2])

6


In [26]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5])

[2 3 4 5]


In [27]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[4:])

[5 6 7]


In [28]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[-3:-1])

[5 6]
